//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ryanair.Reservation.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ryanair.Reservation.Domain.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card could not be empty..
        /// </summary>
        internal static string CreditCardNullEmprty {
            get {
                return ResourceManager.GetString("CreditCardNullEmprty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email could not be empty..
        /// </summary>
        internal static string EmailNullEmpty {
            get {
                return ResourceManager.GetString("EmailNullEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Flight {0} does not exists..
        /// </summary>
        internal static string FlightNotExists {
            get {
                return ResourceManager.GetString("FlightNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight key could not be empty..
        /// </summary>
        internal static string FlightNullEmpty {
            get {
                return ResourceManager.GetString("FlightNullEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seat Number {0} is not valid..
        /// </summary>
        internal static string InvalidSeatNumber {
            get {
                return ResourceManager.GetString("InvalidSeatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passenger {0} cannot carry more then 5 bags..
        /// </summary>
        internal static string MaxBagsPerUser {
            get {
                return ResourceManager.GetString("MaxBagsPerUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are more then 2 flight in the request..
        /// </summary>
        internal static string MoreThenTwoFlights {
            get {
                return ResourceManager.GetString("MoreThenTwoFlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There ins`t flight information in request..
        /// </summary>
        internal static string NoFlightInformation {
            get {
                return ResourceManager.GetString("NoFlightInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passenger Information is missing..
        /// </summary>
        internal static string PaasengerInformationMissing {
            get {
                return ResourceManager.GetString("PaasengerInformationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passenger name is required..
        /// </summary>
        internal static string PassengerNameRequired {
            get {
                return ResourceManager.GetString("PassengerNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seat number {0} is already in use for flight {1}..
        /// </summary>
        internal static string SeatInUse {
            get {
                return ResourceManager.GetString("SeatInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not convert {0} to number..
        /// </summary>
        internal static string SeatNumberError {
            get {
                return ResourceManager.GetString("SeatNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The seat number is mandatory..
        /// </summary>
        internal static string SeatNumberMandatory {
            get {
                return ResourceManager.GetString("SeatNumberMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There isn`t enought space for {0} bags in {1} flight..
        /// </summary>
        internal static string ThereIsNoSpaceForBags {
            get {
                return ResourceManager.GetString("ThereIsNoSpaceForBags", resourceCulture);
            }
        }
    }
}
