<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Class1.cs" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Repositories\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ryanair.Reservation.Domain\Ryanair.Reservation.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="InitialState.json" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="InitialState.json" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="12.0.2" />
  </ItemGroup>
</Project>
