<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.8.0" />
    <PackageReference Include="xunit" Version="2.4.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.0" />
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Ryanair.Reservation\Ryanair.Reservation.csproj" />
    <ProjectReference Include="..\..\src\Ryanair.Reservation.Domain\Ryanair.Reservation.Domain.csproj" />
    <ProjectReference Include="..\..\src\Ryanair.Reservation.Infrastructure\Ryanair.Reservation.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Domain\" />
    <Folder Include="Domain\Entities\" />
    <Folder Include="Domain\Entities\FlightAggregate\" />
    <Folder Include="Domain\Entities\ReservationAggregate\" />
    <Folder Include="Domain\Services\" />
    <Folder Include="Application\" />
    <Folder Include="Application\Mediator\" />
    <Folder Include="Application\Mediator\Commands\" />
    <Folder Include="Application\Mediator\Queries\" />
    <Folder Include="Application\Mediator\Queries\Flight\" />
  </ItemGroup>
</Project>
