//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ryanair.Reservation.Domain.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ryanair.Reservation.Domain.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CreditCardNullEmprty {
            get {
                return ResourceManager.GetString("CreditCardNullEmprty", resourceCulture);
            }
        }
        
        internal static string EmailNullEmpty {
            get {
                return ResourceManager.GetString("EmailNullEmpty", resourceCulture);
            }
        }
        
        internal static string FlightNotExists {
            get {
                return ResourceManager.GetString("FlightNotExists", resourceCulture);
            }
        }
        
        internal static string FlightNullEmpty {
            get {
                return ResourceManager.GetString("FlightNullEmpty", resourceCulture);
            }
        }
        
        internal static string InvalidSeatNumber {
            get {
                return ResourceManager.GetString("InvalidSeatNumber", resourceCulture);
            }
        }
        
        internal static string MaxBagsPerUser {
            get {
                return ResourceManager.GetString("MaxBagsPerUser", resourceCulture);
            }
        }
        
        internal static string MoreThenTwoFlights {
            get {
                return ResourceManager.GetString("MoreThenTwoFlights", resourceCulture);
            }
        }
        
        internal static string NoFlightInformation {
            get {
                return ResourceManager.GetString("NoFlightInformation", resourceCulture);
            }
        }
        
        internal static string PaasengerInformationMissing {
            get {
                return ResourceManager.GetString("PaasengerInformationMissing", resourceCulture);
            }
        }
        
        internal static string PassengerNameRequired {
            get {
                return ResourceManager.GetString("PassengerNameRequired", resourceCulture);
            }
        }
        
        internal static string SeatInUse {
            get {
                return ResourceManager.GetString("SeatInUse", resourceCulture);
            }
        }
        
        internal static string SeatNumberError {
            get {
                return ResourceManager.GetString("SeatNumberError", resourceCulture);
            }
        }
        
        internal static string SeatNumberMandatory {
            get {
                return ResourceManager.GetString("SeatNumberMandatory", resourceCulture);
            }
        }
        
        internal static string ThereIsNoSpaceForBags {
            get {
                return ResourceManager.GetString("ThereIsNoSpaceForBags", resourceCulture);
            }
        }
    }
}
